apiVersion: v1
kind: Secret
metadata:
  name: sysdig-agent
  labels:
    app: sysdig-agent
type: Opaque
data:
 access-key: "replace with echo -n 'your-key' | base64"
 tags: "replace with your tags, like echo -n 'cluster:kubernetes' | base64"
